/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hallmanagement;
import java.io.*;
import javax.swing.*;
/**
 *
 * @author ron_debajyoti
 */
public class ChangingHalls extends javax.swing.JFrame {

    private final String name;
    public  boolean flag;
    /**
     * Creates new form ChangingHalls
     */
    public ChangingHalls(String input,boolean flag) {
        initComponents();
        this.name=input;
        this.flag=flag;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        HallNames = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        continueButton = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        hallButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Waree", 1, 22)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(8, 1, 1));
        jLabel1.setText("Changing Halls ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(93, 12, 205, 68));

        jLabel2.setText("The Following halls are currently vacant.");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 86, 334, 43));

        HallNames.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", " " }));
        HallNames.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HallNamesActionPerformed(evt);
            }
        });
        getContentPane().add(HallNames, new org.netbeans.lib.awtextra.AbsoluteConstraints(89, 182, 178, -1));

        jLabel3.setText("Please select from the drop-down menu :::");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 135, 334, 35));

        jLabel4.setText("Do you wish to continue the process ? ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 256, 308, 42));

        continueButton.setText("Continue");
        continueButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                continueButtonActionPerformed(evt);
            }
        });
        getContentPane().add(continueButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 304, 102, -1));

        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 352, 102, -1));

        hallButton.setText("Hall List");
        hallButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hallButtonActionPerformed(evt);
            }
        });
        getContentPane().add(hallButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, 120, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hallmanagement/template3.jpg"))); // NOI18N
        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void continueButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_continueButtonActionPerformed
        // TODO add your handling code here:
        String hallname,line,p="";
        try{
            FileReader fr = new FileReader("hall.txt");
            BufferedReader br = new BufferedReader(fr);
            while((line = br.readLine())!= null) {
                   if(HallNames.getSelectedItem().toString().equals(line.substring(line.indexOf('-')+1,line.indexOf('$'))))
                   {
                       hallname=line.substring(line.indexOf('-')+1,line.length());
                       File f = new File("hallchange-"+name+".txt");
                       FileWriter out = new FileWriter(f,true);
                       PrintWriter o = new PrintWriter(out);
                       o.println("Changing Hall:: ");
                       o.println("Username: "+name);                        
                       o.println("Requested Hall Change::"+hallname+"#");
                       o.close();
                       out.close();
                       JOptionPane.showMessageDialog(this,"You have sucessfully applied for Hall Change","Notice",JOptionPane.INFORMATION_MESSAGE);
                       flag=true;
                       break;
                   }                                    
               }
            br.close();
        }catch (FileNotFoundException ex) {
            JOptionPane.showMessageDialog(this,ex,"Error",JOptionPane.ERROR_MESSAGE);
        } catch (IOException ex) {
           JOptionPane.showMessageDialog(this,ex,"Error",JOptionPane.ERROR_MESSAGE);
        }
        dispose();
    }//GEN-LAST:event_continueButtonActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void hallButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hallButtonActionPerformed
        // TODO add your handling code here:
        String line;
        String p = "";
        try {
            // TODO add your handling code here:
            FileReader fr = new FileReader("hall.txt");
            BufferedReader br = new BufferedReader(fr);
            while ((line = br.readLine()) != null) {
                   p = p+line +"\n";                  
               }
            br.close();
            JOptionPane.showMessageDialog(this,p," Profile",JOptionPane.INFORMATION_MESSAGE);
        } catch (FileNotFoundException ex) {
            JOptionPane.showMessageDialog(this,ex,"Error",JOptionPane.ERROR_MESSAGE);
        } catch (IOException ex) {
           JOptionPane.showMessageDialog(this,ex,"Error",JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_hallButtonActionPerformed

    private void HallNamesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HallNamesActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_HallNamesActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> HallNames;
    private javax.swing.JButton continueButton;
    private javax.swing.JButton hallButton;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
