/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hallmanagement;

import java.awt.Color;
import javax.swing.JOptionPane;
import java.io.*;

/**
 *
 * @author ron_debajyoti
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        setTitle("Login Page");
        setBackground(Color.yellow);
    }

    public boolean logcheck(String user,String password,String input){
        boolean bol = false;
        String out = user+"#"+password;
        String line;
        if(input.equals("Student")){
            try {
                FileReader fr = new FileReader("student.txt");
                BufferedReader br = new BufferedReader(fr);
                while ((line=br.readLine())!= null) 
                {
                    if(line.equals(out)){
                        bol = true;
                        break;
                    }
                }
                br.close();
            } catch (FileNotFoundException ex) {
                JOptionPane.showMessageDialog(this,ex,"Error",JOptionPane.ERROR_MESSAGE);
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(this,ex,"Error",JOptionPane.ERROR_MESSAGE);
            }
        }
        else if(input.equals("Administrator")){
            try {
                FileReader fr = new FileReader("admin.txt");
                BufferedReader br = new BufferedReader(fr);
                while ((line = br.readLine()) != null) {
                    if(line.equals(out)){
                        bol = true;
                        break;
                    }
                }
                br.close();
            } catch (FileNotFoundException ex) {
                JOptionPane.showMessageDialog(this,ex,"Error",JOptionPane.ERROR_MESSAGE);
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(this,ex,"Error",JOptionPane.ERROR_MESSAGE);
            }
        }
        return bol;
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        usernameLayout = new javax.swing.JLabel();
        passwordLayout = new javax.swing.JLabel();
        studentUsernameArea = new javax.swing.JTextField();
        loginStudentButton = new javax.swing.JButton();
        cancelStudentButton = new javax.swing.JButton();
        pic = new javax.swing.JLabel();
        studentPasswordArea = new javax.swing.JPasswordField();
        studentNamePlate = new javax.swing.JLabel();
        adminNamePlate = new javax.swing.JLabel();
        adUsername = new javax.swing.JLabel();
        adPassword = new javax.swing.JLabel();
        adminUsernameArea = new javax.swing.JTextField();
        adminPasswordArea = new javax.swing.JPasswordField();
        loginAdminButton = new javax.swing.JButton();
        cancelAdminButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        setBackground(java.awt.Color.yellow);
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setMinimumSize(new java.awt.Dimension(600, 600));
        setPreferredSize(new java.awt.Dimension(100, 100));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        usernameLayout.setText("Username");
        getContentPane().add(usernameLayout, new org.netbeans.lib.awtextra.AbsoluteConstraints(179, 51, 101, 29));

        passwordLayout.setText("Password");
        getContentPane().add(passwordLayout, new org.netbeans.lib.awtextra.AbsoluteConstraints(179, 118, 101, 26));

        studentUsernameArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentUsernameAreaActionPerformed(evt);
            }
        });
        getContentPane().add(studentUsernameArea, new org.netbeans.lib.awtextra.AbsoluteConstraints(359, 51, 206, -1));

        loginStudentButton.setText("Login");
        loginStudentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginStudentButtonActionPerformed(evt);
            }
        });
        getContentPane().add(loginStudentButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(179, 200, 86, -1));

        cancelStudentButton.setText("Cancel");
        cancelStudentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelStudentButtonActionPerformed(evt);
            }
        });
        getContentPane().add(cancelStudentButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(425, 200, 86, -1));

        pic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hallmanagement/anonym.png"))); // NOI18N
        getContentPane().add(pic, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 12, 167, 191));
        getContentPane().add(studentPasswordArea, new org.netbeans.lib.awtextra.AbsoluteConstraints(359, 117, 206, -1));

        studentNamePlate.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        studentNamePlate.setForeground(new java.awt.Color(235, 28, 28));
        studentNamePlate.setText("For Students:::");
        getContentPane().add(studentNamePlate, new org.netbeans.lib.awtextra.AbsoluteConstraints(179, 12, 162, 33));

        adminNamePlate.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        adminNamePlate.setForeground(new java.awt.Color(236, 52, 52));
        adminNamePlate.setText("For Administrators:::     ");
        getContentPane().add(adminNamePlate, new org.netbeans.lib.awtextra.AbsoluteConstraints(179, 248, 398, 38));

        adUsername.setText("Username");
        getContentPane().add(adUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(179, 298, 112, 36));

        adPassword.setText("Password");
        getContentPane().add(adPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(179, 379, 112, 36));
        getContentPane().add(adminUsernameArea, new org.netbeans.lib.awtextra.AbsoluteConstraints(359, 302, 206, -1));
        getContentPane().add(adminPasswordArea, new org.netbeans.lib.awtextra.AbsoluteConstraints(359, 379, 206, -1));

        loginAdminButton.setText("Login");
        loginAdminButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginAdminButtonActionPerformed(evt);
            }
        });
        getContentPane().add(loginAdminButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(179, 429, 86, -1));

        cancelAdminButton.setText("Cancel");
        cancelAdminButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelAdminButtonActionPerformed(evt);
            }
        });
        getContentPane().add(cancelAdminButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(419, 429, 86, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hallmanagement/99166-200.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 248, 155, 211));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hallmanagement/template5.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 660, 590));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void studentUsernameAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentUsernameAreaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_studentUsernameAreaActionPerformed

    private void loginStudentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginStudentButtonActionPerformed
    // TODO add your handling code here:
        if(logcheck(studentUsernameArea.getText(),studentPasswordArea.getText(),"Student")){
            StudentPage sp = new StudentPage(studentUsernameArea.getText());
            sp.setVisible(true);
            dispose();
        }
        else{
            JOptionPane.showMessageDialog(this,"Invalid Student Username/Password","Error",JOptionPane.ERROR_MESSAGE);
            studentUsernameArea.setText("");
            studentPasswordArea.setText("");
            adminUsernameArea.setText("");
            adminPasswordArea.setText("");
            studentUsernameArea.requestFocus();
        }
        
    
    }//GEN-LAST:event_loginStudentButtonActionPerformed

    private void cancelStudentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelStudentButtonActionPerformed
        dispose();
    // TODO add your handling code here:
    }//GEN-LAST:event_cancelStudentButtonActionPerformed

    private void loginAdminButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginAdminButtonActionPerformed
        
        if(logcheck(adminUsernameArea.getText(),adminPasswordArea.getText(),"Administrator")){
            Admin ad = new Admin(adminUsernameArea.getText());
            ad.setVisible(true);
            dispose();
        }
        else{
            JOptionPane.showMessageDialog(this,"Invalid Admin Username/Password","Error",JOptionPane.ERROR_MESSAGE);
            studentUsernameArea.setText("");
            studentPasswordArea.setText("");
            adminUsernameArea.setText("");
            adminPasswordArea.setText("");
            studentUsernameArea.requestFocus();
        }    
    // TODO add your handling code here:
    }//GEN-LAST:event_loginAdminButtonActionPerformed

    private void cancelAdminButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelAdminButtonActionPerformed
       dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_cancelAdminButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel adPassword;
    private javax.swing.JLabel adUsername;
    private javax.swing.JLabel adminNamePlate;
    private javax.swing.JPasswordField adminPasswordArea;
    private javax.swing.JTextField adminUsernameArea;
    private javax.swing.JButton cancelAdminButton;
    private javax.swing.JButton cancelStudentButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton loginAdminButton;
    private javax.swing.JButton loginStudentButton;
    private javax.swing.JLabel passwordLayout;
    private javax.swing.JLabel pic;
    private javax.swing.JLabel studentNamePlate;
    private javax.swing.JPasswordField studentPasswordArea;
    private javax.swing.JTextField studentUsernameArea;
    private javax.swing.JLabel usernameLayout;
    // End of variables declaration//GEN-END:variables
}
