/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hallmanagement;
import java.io.*;
import javax.swing.*;
/**
 *
 * @author ron_debajyoti
 */
public class MutualSwap extends javax.swing.JFrame {
    
    private final String name;
    public boolean flag;
    /**
     * Creates new form MutualSwap
     */
    public MutualSwap(String input,boolean flag) {
        initComponents();
        this.name=input;
        this.flag=flag;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        name2ndArea = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        username2ndArea = new javax.swing.JTextField();
        hall2ndArea = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        applyButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Waree", 1, 18)); // NOI18N
        jLabel1.setText("Mutual Swap");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(199, 12, 153, 54));

        jLabel2.setText("Enter the name of 2nd student : ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 72, 282, 41));
        getContentPane().add(name2ndArea, new org.netbeans.lib.awtextra.AbsoluteConstraints(306, 78, 198, -1));

        jLabel3.setText("Enter the hall of 2nd Student :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 208, 274, 47));

        jLabel4.setText("Enter the username of 2nd Student :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 134, 274, 47));
        getContentPane().add(username2ndArea, new org.netbeans.lib.awtextra.AbsoluteConstraints(304, 143, 198, -1));
        getContentPane().add(hall2ndArea, new org.netbeans.lib.awtextra.AbsoluteConstraints(304, 217, 198, -1));

        jLabel5.setText("Do you wish to apply for mutual swap ?");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(97, 294, 335, 38));

        applyButton.setText("Apply");
        applyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                applyButtonActionPerformed(evt);
            }
        });
        getContentPane().add(applyButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(97, 359, 95, -1));

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        getContentPane().add(cancelButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(278, 359, 111, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hallmanagement/template7.jpg"))); // NOI18N
        jLabel6.setText("jLabel6");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 570, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void applyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_applyButtonActionPerformed
        // TODO add your handling code here:
        try
        {
            File f = new File("mutual-"+name+".txt");
        
        FileWriter out = new FileWriter(f,true);
        PrintWriter o = new PrintWriter(out);
        o.println("Mutual Swap :-");
        o.println("Username of 2nd Student: "+username2ndArea.getText());
        o.println("Name of 2nd Student: "+name2ndArea.getText());
        o.println("Hall of 2nd Student: "+hall2ndArea.getText());
        o.close();
        out.close();                        
        JOptionPane.showMessageDialog(this,"You have sucessfully applied for Mutual Swap","Mutual Swap",JOptionPane.INFORMATION_MESSAGE);
        dispose();
        }
        catch(IOException e){
                        JOptionPane.showMessageDialog(this,"Could not open file","Error",JOptionPane.ERROR_MESSAGE);
                    }
        
    }//GEN-LAST:event_applyButtonActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton applyButton;
    private javax.swing.JButton cancelButton;
    private javax.swing.JTextField hall2ndArea;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField name2ndArea;
    private javax.swing.JTextField username2ndArea;
    // End of variables declaration//GEN-END:variables
}
