/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hallmanagement;
import java.io.*;
import javax.swing.*;
/**
 *
 * @author ron_debajyoti
 */
public class Notif extends javax.swing.JFrame {

    /**
     * Creates new form Notif
     */
    private final String name;
    public Notif(String input) {
        initComponents();
        this.name=input;
        String line;
        try{
        FileReader fr = new FileReader("std-"+name+".txt");
            BufferedReader br = new BufferedReader(fr);
            while((line = br.readLine()) != null) {
                  jLabel1.setText(line);                  
               }
            br.close();
        }
        catch (IOException ex) {
               JOptionPane.showMessageDialog(this,ex,"Error",JOptionPane.ERROR_MESSAGE);
           }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        approveButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Waree", 1, 19)); // NOI18N
        jLabel1.setText("   Notification Centre");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(73, 12, 247, 37);
        getContentPane().add(jLabel2);
        jLabel2.setBounds(33, 67, 331, 144);

        approveButton.setText("Approve");
        approveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                approveButtonActionPerformed(evt);
            }
        });
        getContentPane().add(approveButton);
        approveButton.setBounds(116, 235, 134, 30);

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        getContentPane().add(cancelButton);
        cancelButton.setBounds(113, 277, 137, 30);

        jLabel3.setIcon(new javax.swing.ImageIcon("/home/ron_debajyoti/Pictures/template7.jpg")); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 460, 450);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void approveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_approveButtonActionPerformed
        // TODO add your handling code here:
        try
        {
            String s,s1;
            File f= new File("std-"+name+".txt");
            File f1= new File("hallchange-"+name+".txt");
            FileReader fr1 = new FileReader(f1);
            FileReader fr = new FileReader(f);
            BufferedReader br1 = new BufferedReader(fr1);
            s1=br1.readLine();
            BufferedReader br = new BufferedReader(fr);
            while((s = br.readLine()) != null)
            {
                s.replaceAll(s1.substring(s1.indexOf("Requested Hall Change::")+1,s1.indexOf("#")),s.substring(s.indexOf("Hall of Residence::"),s.indexOf("$$")));
            }
            JOptionPane.showMessageDialog(this,"Approved","Update Info",JOptionPane.INFORMATION_MESSAGE);
        }  
        catch(IOException e){
                        JOptionPane.showMessageDialog(this,"Couldn't open the file","Error",JOptionPane.ERROR_MESSAGE);
                    }
        dispose();
    }//GEN-LAST:event_approveButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton approveButton;
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
