/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hallmanagement;
import java.io.*;
/**
 *
 * @author ron_debajyoti
 */
public class StudentPage extends javax.swing.JFrame {

    private final String name;
    private boolean flag=false;
    /**
     * Creates new form StudentPage
     */
    public StudentPage(String input) {
        initComponents();
        this.name=input;
        setTitle("Students' Page");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        updateProfileButton = new javax.swing.JButton();
        changingHallButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        mutualSwapButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        updateProfileButton.setText("Select");
        updateProfileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateProfileButtonActionPerformed(evt);
            }
        });
        getContentPane().add(updateProfileButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(257, 120, -1, -1));

        changingHallButton.setText("Select");
        changingHallButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changingHallButtonActionPerformed(evt);
            }
        });
        getContentPane().add(changingHallButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(257, 214, -1, -1));

        jLabel1.setFont(new java.awt.Font("Waree", 1, 22)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 28));
        jLabel1.setText("        Student Page");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 11, 306, 83));

        jLabel2.setFont(new java.awt.Font("Ubuntu Light", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(26, 16, 16));
        jLabel2.setText("Mutual Swap");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 310, 192, 67));

        jLabel3.setFont(new java.awt.Font("Ubuntu Light", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(26, 16, 16));
        jLabel3.setText("Update/View Profile ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 100, 192, 67));

        jLabel4.setFont(new java.awt.Font("Ubuntu Light", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(26, 16, 16));
        jLabel4.setText("Changing Halls");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 194, 192, 67));

        mutualSwapButton.setText("Select");
        mutualSwapButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mutualSwapButtonActionPerformed(evt);
            }
        });
        getContentPane().add(mutualSwapButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(257, 330, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hallmanagement/student.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(378, 100, 177, 297));

        jButton4.setText("Cancel");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 380, 90, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hallmanagement/template6.jpg"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void changingHallButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changingHallButtonActionPerformed
        // TODO add your handling code here:
        ChangingHalls ch = new ChangingHalls(name,flag);
        ch.setVisible(true);
    }//GEN-LAST:event_changingHallButtonActionPerformed

    private void mutualSwapButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mutualSwapButtonActionPerformed
        // TODO add your handling code here:
        MutualSwap ms= new MutualSwap(name,flag);
        ms.setVisible(true);
    }//GEN-LAST:event_mutualSwapButtonActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void updateProfileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateProfileButtonActionPerformed
        // TODO add your handling code here:
        UpdateorView up = new UpdateorView(name);
        up.setVisible(true);
    }//GEN-LAST:event_updateProfileButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton changingHallButton;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JButton mutualSwapButton;
    private javax.swing.JButton updateProfileButton;
    // End of variables declaration//GEN-END:variables
}
